// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"database/sql"
)

type ExtraPort struct {
	ID     int64  `json:"id"`
	HostID int64  `json:"host_id"`
	State  string `json:"state"`
	Count  int64  `json:"count"`
}

type ExtraPortsReason struct {
	ID          int64  `json:"id"`
	ExtraPortID int64  `json:"extra_port_id"`
	Reason      string `json:"reason"`
	Count       int64  `json:"count"`
	Proto       string `json:"proto"`
	Ports       string `json:"ports"`
}

type Host struct {
	ID                    int64          `json:"id"`
	ScanID                int64          `json:"scan_id"`
	StartTime             int64          `json:"start_time"`
	EndTime               int64          `json:"end_time"`
	StatusState           string         `json:"status_state"`
	StatusReason          string         `json:"status_reason"`
	StatusReasonTtl       int64          `json:"status_reason_ttl"`
	DistanceValue         int64          `json:"distance_value"`
	UptimeSeconds         int64          `json:"uptime_seconds"`
	UptimeLastboot        string         `json:"uptime_lastboot"`
	TcpSequenceIndex      int64          `json:"tcp_sequence_index"`
	TcpSequenceDifficulty string         `json:"tcp_sequence_difficulty"`
	TcpSequenceValues     string         `json:"tcp_sequence_values"`
	IpIDSeqClass          string         `json:"ip_id_seq_class"`
	IpIDSeqValues         string         `json:"ip_id_seq_values"`
	TcpTsSeqClass         sql.NullString `json:"tcp_ts_seq_class"`
	TcpTsSeqValues        sql.NullString `json:"tcp_ts_seq_values"`
	TimeSrtt              int64          `json:"time_srtt"`
	TimeRttvar            int64          `json:"time_rttvar"`
	TimeTo                int64          `json:"time_to"`
}

type HostAddress struct {
	ID       int64  `json:"id"`
	HostID   int64  `json:"host_id"`
	Addr     string `json:"addr"`
	AddrType string `json:"addr_type"`
	Vendor   string `json:"vendor"`
}

type HostName struct {
	ID     int64  `json:"id"`
	HostID int64  `json:"host_id"`
	Name   string `json:"name"`
	Type   string `json:"type"`
}

type HostScript struct {
	ID           int64  `json:"id"`
	HostID       int64  `json:"host_id"`
	ScriptID     string `json:"script_id"`
	ScriptOutput string `json:"script_output"`
}

type HostScriptElement struct {
	ID           int64  `json:"id"`
	HostScriptID int64  `json:"host_script_id"`
	Key          string `json:"key"`
	Value        string `json:"value"`
}

type HostTrace struct {
	ID     int64  `json:"id"`
	HostID int64  `json:"host_id"`
	Port   int64  `json:"port"`
	Proto  string `json:"proto"`
}

type OsClass struct {
	ID        int64  `json:"id"`
	OsMatchID int64  `json:"os_match_id"`
	Type      string `json:"type"`
	Vendor    string `json:"vendor"`
	Osfamily  string `json:"osfamily"`
	Osgen     string `json:"osgen"`
	Accuracy  string `json:"accuracy"`
	Cpe       string `json:"cpe"`
}

type OsMatch struct {
	ID       int64  `json:"id"`
	HostID   int64  `json:"host_id"`
	Name     string `json:"name"`
	Accuracy string `json:"accuracy"`
	Line     string `json:"line"`
}

type OsPortsUsed struct {
	ID       int64  `json:"id"`
	HostID   int64  `json:"host_id"`
	State    string `json:"state"`
	Protocol string `json:"protocol"`
	PortID   int64  `json:"port_id"`
}

type Port struct {
	ID               int64  `json:"id"`
	HostID           int64  `json:"host_id"`
	Protocol         string `json:"protocol"`
	PortID           int64  `json:"port_id"`
	State            string `json:"state"`
	StateReason      string `json:"state_reason"`
	StateReasonTtl   int64  `json:"state_reason_ttl"`
	ServiceName      string `json:"service_name"`
	ServiceConf      int64  `json:"service_conf"`
	ServiceMethod    string `json:"service_method"`
	ServiceVersion   string `json:"service_version"`
	ServiceProduct   string `json:"service_product"`
	ServiceExtraInfo string `json:"service_extra_info"`
	ServiceTunnel    string `json:"service_tunnel"`
	ServiceProto     string `json:"service_proto"`
	ServiceRpcNum    string `json:"service_rpc_num"`
	ServiceLowver    string `json:"service_lowver"`
	ServiceHighver   string `json:"service_highver"`
	ServiceFp        string `json:"service_fp"`
}

type PortScript struct {
	ID           int64  `json:"id"`
	PortID       int64  `json:"port_id"`
	ScriptID     string `json:"script_id"`
	ScriptOutput string `json:"script_output"`
}

type PortScriptElement struct {
	ID           int64  `json:"id"`
	PortScriptID int64  `json:"port_script_id"`
	Key          string `json:"key"`
	Value        string `json:"value"`
}

type PortServiceCpe struct {
	ID     int64  `json:"id"`
	PortID int64  `json:"port_id"`
	Cpe    string `json:"cpe"`
}

type Scan struct {
	ID                  int64           `json:"id"`
	Scanner             string          `json:"scanner"`
	Args                string          `json:"args"`
	Start               int64           `json:"start"`
	StartStr            string          `json:"start_str"`
	Version             string          `json:"version"`
	XmlOutputVersion    string          `json:"xml_output_version"`
	ScanInfoType        sql.NullString  `json:"scan_info_type"`
	ScanInfoProtocol    sql.NullString  `json:"scan_info_protocol"`
	ScanInfoNumServices sql.NullInt64   `json:"scan_info_num_services"`
	ScanInfoServices    sql.NullString  `json:"scan_info_services"`
	VerboseLevel        sql.NullInt64   `json:"verbose_level"`
	DebuggingLevel      sql.NullInt64   `json:"debugging_level"`
	RunstatsTime        sql.NullInt64   `json:"runstats_time"`
	RunstatsTimeStr     sql.NullString  `json:"runstats_time_str"`
	RunstatsElapsed     sql.NullFloat64 `json:"runstats_elapsed"`
	RunstatsSummary     sql.NullString  `json:"runstats_summary"`
	RunstatsExit        sql.NullString  `json:"runstats_exit"`
	RunstatsErr         sql.NullString  `json:"runstats_err"`
	HostsUp             sql.NullInt64   `json:"hosts_up"`
	HostsDown           sql.NullInt64   `json:"hosts_down"`
	HostsTotal          sql.NullInt64   `json:"hosts_total"`
}

type TraceHop struct {
	ID      int64   `json:"id"`
	TraceID int64   `json:"trace_id"`
	Ttl     int64   `json:"ttl"`
	IpAddr  string  `json:"ip_addr"`
	Rtt     float64 `json:"rtt"`
	Host    string  `json:"host"`
}
