# Used to regenerate the code for the custom queries if needed
version: "2"
sql:
  - engine: "sqlite"
    schema: "internal/db/schema.sql"
    queries: "internal/db/custom.sql"
    gen:
      go:
        package: "sqlc"
        out: "pkg/db"
        emit_interface: false
        emit_json_tags: true
        emit_prepared_queries: false
        emit_exact_table_names: false
        emit_empty_slices: true
